### ISSUE TITLE
Speedtest CLI - python errors

### ISSUE THREAD

**Issue by ChrisWNY** [arevindh/pihole-speedtest#82]
When using official Speedtest CLI...

Noticed today that when I attempted to run speedtest manually via the command line, I'd get the following error:

<code>sudo pihole -a -sn

Testing Speed
Traceback (most recent call last):
  File "/usr/local/bin/speedtest-cli", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/speedtest.py", line 1930, in main
    shell()
  File "/usr/local/lib/python2.7/dist-packages/speedtest.py", line 1819, in shell
    secure=args.secure
  File "/usr/local/lib/python2.7/dist-packages/speedtest.py", line 1053, in __init__
    self.get_config()
  File "/usr/local/lib/python2.7/dist-packages/speedtest.py", line 1136, in get_config
    map(int, server_config['ignoreids'].split(','))
ValueError: invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "/usr/local/bin/speedtest-cli", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/speedtest.py", line 1930, in main
    shell()
  File "/usr/local/lib/python2.7/dist-packages/speedtest.py", line 1819, in shell
    secure=args.secure
  File "/usr/local/lib/python2.7/dist-packages/speedtest.py", line 1053, in __init__
    self.get_config()
  File "/usr/local/lib/python2.7/dist-packages/speedtest.py", line 1136, in get_config
    map(int, server_config['ignoreids'].split(','))
ValueError: invalid literal for int() with base 10: ''
Connection Failed Retry after 30 sec Connection Failed Retry failed aborting
</code>

Not sure if this was caused by a recent update to python modules or something else. Thought I'd post in hopes that further info could be provided. Thanks.

**Comment by ChrisWNY** [comment]
You can close this issue...the python speedtest module was old, v2.0.3. Updating the module corrected the issue.

sudo  python3 -m pip install --upgrade speedtest-cli

**Comment by evanrh** [comment]
You can fix this error by commenting out lines 1113-1115 by placing a '#' at the beginning of each.
After commenting them out, add `ignore_servers = []` on line 1116.

**Comment by arevindh** [comment]
`sudo pihole -a -sn` this thing is not working anymore .. 

use `sudo "/var/www/html/admin/scripts/pi-hole/speedtest/speedtest-official.sh" `
